using System.Collections.Generic;
using EloBuddy;

namespace Mario_s_Lib.DataBases
{
    public class Skin
    {
        public Champion Champ;
        public List<string> Skins;
        public Skin(Champion champ, List<string> skins)
        {
            Champ = champ;
            Skins = skins;
        }
    }

    public static class Skins
    {
        public static List<Skin> SkinsDB = new List<Skin>
        {
            new Skin(Champion.Aatrox, new List<string> {"Basic Skin", "Justicar Aatrox", "Mecha Aatrox", "Sea Hunter Aatrox"}),
            new Skin(Champion.Ahri, new List<string> {"Basic Skin","Dynasty Ahri", "Midnight Ahri", "Foxfire Ahri", "Popstar Ahri", "Challenger Ahri", "Academy Ahri"}),
            new Skin(Champion.Akali, new List<string> {"Basic Skin","Stinger Akali", "Crimson Akali", }),
            new Skin(Champion.Alistar, new List<string> {"Basic Skin",}),
            new Skin(Champion.Amumu, new List<string> {"Basic Skin",}),
            new Skin(Champion.Anivia, new List<string> {"Basic Skin",}),
            new Skin(Champion.Annie, new List<string> {"Basic Skin",}),
            new Skin(Champion.Ashe, new List<string> {"Basic Skin",}),
            new Skin(Champion.AurelionSol, new List<string> {"Basic Skin",}),
            new Skin(Champion.Azir, new List<string> {"Basic Skin",}),
            new Skin(Champion.Bard, new List<string> {"Basic Skin",}),
            new Skin(Champion.Blitzcrank, new List<string> {"Basic Skin",}),
            new Skin(Champion.Brand, new List<string> {"Basic Skin",}),
            new Skin(Champion.Braum, new List<string> {"Basic Skin",}),
            new Skin(Champion.Caitlyn, new List<string> {"Basic Skin",}),
            new Skin(Champion.Cassiopeia, new List<string> {"Basic Skin",}),
            new Skin(Champion.Chogath, new List<string> {"Basic Skin",}),
            new Skin(Champion.Corki, new List<string> {"Basic Skin",}),
            new Skin(Champion.Darius, new List<string> {"Basic Skin",}),
            new Skin(Champion.Diana, new List<string> {"Basic Skin",}),
            new Skin(Champion.DrMundo, new List<string> {"Basic Skin",}),
            new Skin(Champion.Draven, new List<string> {"Basic Skin",}),
            new Skin(Champion.Ekko, new List<string> {"Basic Skin",}),
            new Skin(Champion.Elise, new List<string> {"Basic Skin",}),
            new Skin(Champion.Evelynn, new List<string> {"Basic Skin",}),
            new Skin(Champion.Ezreal, new List<string> {"Basic Skin",}),
            new Skin(Champion.FiddleSticks, new List<string> {"Basic Skin",}),
            new Skin(Champion.Fiora, new List<string> {"Basic Skin",}),
            new Skin(Champion.Fizz, new List<string> {"Basic Skin",}),
            new Skin(Champion.Galio, new List<string> {"Basic Skin",}),
            new Skin(Champion.Gangplank, new List<string> {"Basic Skin",}),
            new Skin(Champion.Garen, new List<string> {"Basic Skin",}),
            new Skin(Champion.Gnar, new List<string> {"Basic Skin",}),
            new Skin(Champion.Gragas, new List<string> {"Basic Skin",}),
            new Skin(Champion.Graves, new List<string> {"Basic Skin",}),
            new Skin(Champion.Hecarim, new List<string> {"Basic Skin",}),
            new Skin(Champion.Heimerdinger, new List<string> {"Basic Skin",}),
            new Skin(Champion.Illaoi, new List<string> {"Basic Skin",}),
            new Skin(Champion.Irelia, new List<string> {"Basic Skin",}),
            new Skin(Champion.Janna, new List<string> {"Basic Skin",}),
            new Skin(Champion.JarvanIV, new List<string> {"Basic Skin",}),
            new Skin(Champion.Jax, new List<string> {"Basic Skin",}),
            new Skin(Champion.Jayce, new List<string> {"Basic Skin",}),
            new Skin(Champion.Jhin, new List<string> {"Basic Skin",}),
            new Skin(Champion.Jinx, new List<string> {"Basic Skin",}),
            new Skin(Champion.Kalista, new List<string> {"Basic Skin",}),
            new Skin(Champion.Karma, new List<string> {"Basic Skin",}),
            new Skin(Champion.Karthus, new List<string> {"Basic Skin",}),
            new Skin(Champion.Kassadin, new List<string> {"Basic Skin",}),
            new Skin(Champion.Katarina, new List<string> {"Basic Skin",}),
            new Skin(Champion.Kayle, new List<string> {"Basic Skin",}),
            new Skin(Champion.Kennen, new List<string> {"Basic Skin",}),
            new Skin(Champion.Khazix, new List<string> {"Basic Skin",}),
            new Skin(Champion.Kindred, new List<string> {"Basic Skin",}),
            new Skin(Champion.KogMaw, new List<string> {"Basic Skin",}),
            new Skin(Champion.Leblanc, new List<string> {"Basic Skin",}),
            new Skin(Champion.LeeSin, new List<string> {"Basic Skin",}),
            new Skin(Champion.Leona, new List<string> {"Basic Skin",}),
            new Skin(Champion.Lissandra, new List<string> {"Basic Skin",}),
            new Skin(Champion.Lucian, new List<string> {"Basic Skin",}),
            new Skin(Champion.Lulu, new List<string> {"Basic Skin",}),
            new Skin(Champion.Lux, new List<string> {"Basic Skin",}),
            new Skin(Champion.Malphite, new List<string> {"Basic Skin",}),
            new Skin(Champion.Malzahar, new List<string> {"Basic Skin",}),
            new Skin(Champion.Maokai, new List<string> {"Basic Skin",}),
            new Skin(Champion.MasterYi, new List<string> {"Basic Skin",}),
            new Skin(Champion.MissFortune, new List<string> {"Basic Skin",}),
            new Skin(Champion.Mordekaiser, new List<string> {"Basic Skin",}),
            new Skin(Champion.Morgana, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nami, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nasus, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nautilus, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nidalee, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nocturne, new List<string> {"Basic Skin",}),
            new Skin(Champion.Nunu, new List<string> {"Basic Skin",}),
            new Skin(Champion.Olaf, new List<string> {"Basic Skin",}),
            new Skin(Champion.Orianna, new List<string> {"Basic Skin",}),
            new Skin(Champion.Pantheon, new List<string> {"Basic Skin",}),
            new Skin(Champion.Poppy, new List<string> {"Basic Skin",}),
            new Skin(Champion.Quinn, new List<string> {"Basic Skin",}),
            new Skin(Champion.Rammus, new List<string> {"Basic Skin",}),
            new Skin(Champion.RekSai, new List<string> {"Basic Skin",}),
            new Skin(Champion.Renekton, new List<string> {"Basic Skin",}),
            new Skin(Champion.Rengar, new List<string> {"Basic Skin",}),
            new Skin(Champion.Riven, new List<string> {"Basic Skin",}),
            new Skin(Champion.Rumble, new List<string> {"Basic Skin",}),
            new Skin(Champion.Ryze, new List<string> {"Basic Skin",}),
            new Skin(Champion.Sejuani, new List<string> {"Basic Skin",}),
            new Skin(Champion.Shaco, new List<string> {"Basic Skin",}),
            new Skin(Champion.Shen, new List<string> {"Basic Skin",}),
            new Skin(Champion.Shyvana, new List<string> {"Basic Skin",}),
            new Skin(Champion.Singed, new List<string> {"Basic Skin",}),
            new Skin(Champion.Sion, new List<string> {"Basic Skin",}),
            new Skin(Champion.Sivir, new List<string> {"Basic Skin",}),
            new Skin(Champion.Skarner, new List<string> {"Basic Skin",}),
            new Skin(Champion.Sona, new List<string> {"Basic Skin",}),
            new Skin(Champion.Soraka, new List<string> {"Basic Skin",}),
            new Skin(Champion.Swain, new List<string> {"Basic Skin",}),
            new Skin(Champion.Syndra, new List<string> {"Basic Skin",}),
            new Skin(Champion.TahmKench, new List<string> {"Basic Skin",}),
            new Skin(Champion.Talon, new List<string> {"Basic Skin",}),
            new Skin(Champion.Taric, new List<string> {"Basic Skin",}),
            new Skin(Champion.Teemo, new List<string> {"Basic Skin",}),
            new Skin(Champion.Thresh, new List<string> {"Basic Skin",}),
            new Skin(Champion.Tristana, new List<string> {"Basic Skin",}),
            new Skin(Champion.Trundle, new List<string> {"Basic Skin",}),
            new Skin(Champion.Tryndamere, new List<string> {"Basic Skin",}),
            new Skin(Champion.TwistedFate, new List<string> {"Basic Skin",}),
            new Skin(Champion.Twitch, new List<string> {"Basic Skin",}),
            new Skin(Champion.Udyr, new List<string> {"Basic Skin",}),
            new Skin(Champion.Urgot, new List<string> {"Basic Skin",}),
            new Skin(Champion.Varus, new List<string> {"Basic Skin",}),
            new Skin(Champion.Vayne, new List<string> {"Basic Skin",}),
            new Skin(Champion.Veigar, new List<string> {"Basic Skin",}),
            new Skin(Champion.Velkoz, new List<string> {"Basic Skin",}),
            new Skin(Champion.Vi, new List<string> {"Basic Skin",}),
            new Skin(Champion.Viktor, new List<string> {"Basic Skin",}),
            new Skin(Champion.Vladimir, new List<string> {"Basic Skin",}),
            new Skin(Champion.Volibear, new List<string> {"Basic Skin",}),
            new Skin(Champion.Warwick, new List<string> {"Basic Skin",}),
            new Skin(Champion.MonkeyKing, new List<string> {"Basic Skin",}),
            new Skin(Champion.Xerath, new List<string> {"Basic Skin",}),
            new Skin(Champion.XinZhao, new List<string> {"Basic Skin",}),
            new Skin(Champion.Yasuo, new List<string> {"Basic Skin",}),
            new Skin(Champion.Yorick, new List<string> {"Basic Skin",}),
            new Skin(Champion.Zac, new List<string> {"Basic Skin",}),
            new Skin(Champion.Zed, new List<string> {"Basic Skin",}),
            new Skin(Champion.Ziggs, new List<string> {"Basic Skin",}),
            new Skin(Champion.Zilean, new List<string> {"Basic Skin",}),
            new Skin(Champion.Zyra, new List<string> {"Basic Skin",}),
        };
    }
}
